# Generated by Django 4.2.13 on 2026-04-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('session_date', models.DateField(db_index=True, verbose_name='세션 날짜')),
                ('started_at', models.DateTimeField(verbose_name='시작 시각')),
                ('ended_at', models.DateTimeField(verbose_name='종료 시각')),
                ('device_id', models.CharField(blank=True, max_length=64, verbose_name='단말 ID')),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='총 시간(초)')),
                ('iv_seconds', models.PositiveIntegerField(default=0, verbose_name='In Vehicle 시간(초)')),
                ('sr_seconds', models.PositiveIntegerField(default=0, verbose_name='Searching 시간(초)')),
                ('dl_seconds', models.PositiveIntegerField(default=0, verbose_name='Delivering 시간(초)')),
                ('distance_m', models.FloatField(default=0, verbose_name='이동 거리(m)')),
                ('cycle_count', models.PositiveIntegerField(default=0, verbose_name='사이클 수')),
                ('bbox_min_lat', models.FloatField(blank=True, null=True)),
                ('bbox_min_lon', models.FloatField(blank=True, null=True)),
                ('bbox_max_lat', models.FloatField(blank=True, null=True)),
                ('bbox_max_lon', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='crew.crewmember', verbose_name='배송원')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '추적 세션',
                'verbose_name_plural': '추적 세션',
                'ordering': ['-session_date', '-started_at', '-created_at', 'crew_member__code'],
            },
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('cycle_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.CreateModel(
            name='BleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ble_logs', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_m', models.FloatField(default=0)),
                ('speed_kmh', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('IV', 'In Vehicle'), ('SR', 'Searching'), ('DL', 'Delivering')], default='IV', max_length=2)),
                ('cycle_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['session', 'recorded_at'], name='tracking_lo_session_7f60ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.PositiveIntegerField(verbose_name='사이클 번호')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('sr_seconds', models.PositiveIntegerField(default=0)),
                ('dl_seconds', models.PositiveIntegerField(default=0)),
                ('distance_m', models.FloatField(default=0)),
                ('avg_speed_kmh', models.FloatField(default=0)),
                ('avg_accuracy_m', models.FloatField(default=0)),
                ('capture_count', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['cycle_no'],
                'unique_together': {('session', 'cycle_no')},
            },
        ),
    ]
