# Generated by Django 4.2.13 on 2026-04-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveWorkSessionStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("STOPPED", "Stopped"), ("RUNNING", "Running")],
                        db_index=True,
                        default="STOPPED",
                        max_length=16,
                        verbose_name="근무 상태",
                    ),
                ),
                ("current_vehicle_number", models.CharField(blank=True, max_length=20, verbose_name="현재 차량번호")),
                ("session_started_at", models.DateTimeField(blank=True, null=True, verbose_name="근무 시작 시각")),
                ("session_ended_at", models.DateTimeField(blank=True, null=True, verbose_name="근무 종료 시각")),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="마지막 앱 신호")),
                ("background_location_granted", models.BooleanField(default=False, verbose_name="항상 허용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crew_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_work_status",
                        to="crew.crewmember",
                        verbose_name="배송원",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_live_work_session_status",
                "ordering": ["crew_member__team__code", "crew_member__name"],
                "verbose_name": "실시간 근무 상태",
                "verbose_name_plural": "실시간 근무 상태",
            },
        ),
    ]
