# Generated by Django 4.2.13 on 2026-04-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item_key', models.CharField(max_length=64, verbose_name='항목 키')),
                ('item_name', models.CharField(max_length=100, verbose_name='항목명')),
                ('cost_points', models.PositiveIntegerField(verbose_name='사용 포인트')),
                ('status', models.CharField(choices=[('PENDING', '사용 대기'), ('CONFIRMED', '사용 확인'), ('CANCELLED', '취소')], db_index=True, default='PENDING', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인일시')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
            ],
            options={
                'verbose_name': '포인트 교환 요청',
                'verbose_name_plural': '포인트 교환 요청',
                'db_table': 'points_point_redemptions',
                'ordering': ['status', '-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('points', models.IntegerField(verbose_name='포인트')),
                ('kind', models.CharField(choices=[('WORK_REWARD', '근무기록 적립'), ('MANUAL_ADJUST', '수동 수정'), ('REDEMPTION_DEDUCT', '교환 차감')], max_length=32, verbose_name='유형')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('work_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='근무일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='crew.crewmember', verbose_name='배송원')),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='points.pointredemption', verbose_name='교환 요청')),
            ],
            options={
                'verbose_name': '포인트 거래',
                'verbose_name_plural': '포인트 거래',
                'db_table': 'points_point_transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
