# Generated by Django 4.2.13 on 2026-04-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='tracking_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transaction', to='tracking.trackingsession', verbose_name='근무기록'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='pointredemption',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_point_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='확인자'),
        ),
        migrations.AddField(
            model_name='pointredemption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='pointredemption',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_redemptions', to='crew.crewmember', verbose_name='배송원'),
        ),
        migrations.AddField(
            model_name='pointredemption',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['crew_member', 'kind', 'work_date'], name='points_poin_crew_me_f4f7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['kind', 'created_at'], name='points_poin_kind_87275b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointredemption',
            index=models.Index(fields=['status', 'requested_at'], name='points_poin_status_efca28_idx'),
        ),
        migrations.AddIndex(
            model_name='pointredemption',
            index=models.Index(fields=['crew_member', 'status'], name='points_poin_crew_me_9a41e7_idx'),
        ),
    ]
