# Generated by Django 4.2.13 on 2026-04-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_point_items(apps, schema_editor):
    PointItem = apps.get_model("points", "PointItem")
    if PointItem.objects.exists():
        return

    defaults = [
        ("tire_replacement", "타이어 교체", 1000),
        ("car_wash", "세차권", 300),
        ("washer_fluid", "워셔액", 50),
        ("oil_change", "오일교체", 500),
        ("charging_support", "충전비 지원", 200),
        ("delivery_supplies", "배송용품(구르마+장갑)", 200),
        ("replacement_vehicle", "대차권", 2000),
    ]
    PointItem.objects.bulk_create(
        [
            PointItem(
                key=key,
                name=name,
                cost_points=cost_points,
                sort_order=index,
                is_active=True,
            )
            for index, (key, name, cost_points) in enumerate(defaults, start=1)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("points", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64, unique=True, verbose_name="항목 키")),
                ("name", models.CharField(max_length=100, verbose_name="항목명")),
                ("cost_points", models.PositiveIntegerField(verbose_name="필요 포인트")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="정렬 순서")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="사용 여부")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "points_point_items",
                "ordering": ["sort_order", "id"],
                "verbose_name": "포인트 상점 항목",
                "verbose_name_plural": "포인트 상점 항목",
            },
        ),
        migrations.RunPython(seed_point_items, migrations.RunPython.noop),
    ]
