from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


CREATE_SCHEMA_TABLES_SQL = r'''
CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_inspection_schedule" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicle_number" varchar(32) NOT NULL,
    "scheduled_date" date NOT NULL,
    "completed_date" date NULL,
    "status" varchar(16) NOT NULL DEFAULT 'scheduled',
    "memo" text NOT NULL DEFAULT '',
    "source_key" varchar(128) NOT NULL DEFAULT '',
    "raw" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" bigint NULL REFERENCES "public"."accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_id" bigint NULL REFERENCES "vehicle_mgmt"."vehicle" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_record_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_vehicle_record" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_bd0c8a_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("company_id", "scheduled_date");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_fb8bd9_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("company_id", "status");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_531e62_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("company_id", "vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_inspection_schedule_vehicle_number_4c00_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_inspection_schedule_scheduled_date_5ee9_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("scheduled_date");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_inspection_schedule_completed_date_24e5_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("completed_date");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_inspection_schedule_status_9de8_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("status");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_inspection_schedule_source_key_1f62_idx" ON "vehicle_mgmt"."fleet_inspection_schedule" ("source_key");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_profit_rule_version" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "version" varchar(32) NOT NULL,
    "title" varchar(128) NOT NULL DEFAULT '',
    "rules" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" bigint NULL REFERENCES "public"."accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS "vm_fleet_profit_rule_company_version_unique" ON "vehicle_mgmt"."fleet_profit_rule_version" ("company_id", "version");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_rule_version_version_c56f_idx" ON "vehicle_mgmt"."fleet_profit_rule_version" ("version");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_rule_version_is_active_889a_idx" ON "vehicle_mgmt"."fleet_profit_rule_version" ("is_active");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_profit_import_batch" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "source_file" varchar(255) NOT NULL,
    "file_hash" varchar(64) NOT NULL,
    "status" varchar(24) NOT NULL DEFAULT 'applied',
    "summary" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "created_at" timestamptz NOT NULL,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" bigint NULL REFERENCES "public"."accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS "vm_fleet_profit_batch_company_hash_unique" ON "vehicle_mgmt"."fleet_profit_import_batch" ("company_id", "file_hash");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_import_batch_file_hash_02a0_idx" ON "vehicle_mgmt"."fleet_profit_import_batch" ("file_hash");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_import_batch_status_02c0_idx" ON "vehicle_mgmt"."fleet_profit_import_batch" ("status");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_profit_raw_entry" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entry_type" varchar(32) NOT NULL,
    "source_sheet" varchar(64) NOT NULL DEFAULT '',
    "source_row" integer NOT NULL DEFAULT 0 CHECK ("source_row" >= 0),
    "source_key" varchar(160) NOT NULL,
    "vehicle_number" varchar(32) NOT NULL DEFAULT '',
    "period_month" date NULL,
    "amount" integer NOT NULL DEFAULT 0,
    "raw" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "created_at" timestamptz NOT NULL,
    "batch_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_profit_import_batch" ("id") DEFERRABLE INITIALLY DEFERRED,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_id" bigint NULL REFERENCES "vehicle_mgmt"."vehicle" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_record_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_vehicle_record" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS "vm_fleet_profit_raw_company_key_unique" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("company_id", "source_key");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_541089_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("company_id", "entry_type");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_752d2c_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("company_id", "vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_7c7c3f_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("company_id", "period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_raw_entry_entry_type_b8c5_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("entry_type");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_raw_entry_source_key_54de_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("source_key");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_raw_entry_vehicle_number_61c9_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_raw_entry_period_month_3c08_idx" ON "vehicle_mgmt"."fleet_profit_raw_entry" ("period_month");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_profit_adjustment" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicle_number" varchar(32) NOT NULL,
    "period_month" date NOT NULL,
    "category" varchar(64) NOT NULL DEFAULT '',
    "description" text NOT NULL DEFAULT '',
    "amount" integer NOT NULL DEFAULT 0,
    "evidence_file" varchar(100) NOT NULL DEFAULT '',
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" bigint NULL REFERENCES "public"."accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_id" bigint NULL REFERENCES "vehicle_mgmt"."vehicle" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_record_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_vehicle_record" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_11d0aa_idx" ON "vehicle_mgmt"."fleet_profit_adjustment" ("company_id", "period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_011684_idx" ON "vehicle_mgmt"."fleet_profit_adjustment" ("company_id", "vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_adjustment_vehicle_number_b2aa_idx" ON "vehicle_mgmt"."fleet_profit_adjustment" ("vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_adjustment_period_month_6931_idx" ON "vehicle_mgmt"."fleet_profit_adjustment" ("period_month");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_profit_monthly_snapshot" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicle_number" varchar(32) NOT NULL,
    "period_month" date NOT NULL,
    "revenue" integer NOT NULL DEFAULT 0,
    "subscription_revenue" integer NOT NULL DEFAULT 0,
    "customer_charges" integer NOT NULL DEFAULT 0,
    "depreciation_cost" integer NOT NULL DEFAULT 0,
    "insurance_cost" integer NOT NULL DEFAULT 0,
    "repair_cost" integer NOT NULL DEFAULT 0,
    "accident_cost" integer NOT NULL DEFAULT 0,
    "other_cost" integer NOT NULL DEFAULT 0,
    "operating_profit" integer NOT NULL DEFAULT 0,
    "net_profit" integer NOT NULL DEFAULT 0,
    "calculation" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "is_closed" boolean NOT NULL DEFAULT false,
    "closed_at" timestamptz NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED,
    "rule_version_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_profit_rule_version" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_id" bigint NULL REFERENCES "vehicle_mgmt"."vehicle" ("id") DEFERRABLE INITIALLY DEFERRED,
    "vehicle_record_id" bigint NULL REFERENCES "vehicle_mgmt"."fleet_vehicle_record" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS "vm_fleet_profit_month_vehicle_unique" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("company_id", "vehicle_number", "period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_e15ca5_idx" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("company_id", "period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgm_company_7c4cff_idx" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("company_id", "is_closed");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_monthly_snapshot_vehicle_number_de74_idx" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("vehicle_number");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_monthly_snapshot_period_month_fb3a_idx" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_profit_monthly_snapshot_is_closed_4323_idx" ON "vehicle_mgmt"."fleet_profit_monthly_snapshot" ("is_closed");

CREATE TABLE IF NOT EXISTS "vehicle_mgmt"."fleet_monthly_close" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "period_month" date NOT NULL,
    "target" varchar(32) NOT NULL DEFAULT 'profit',
    "status" varchar(24) NOT NULL DEFAULT 'open',
    "memo" text NOT NULL DEFAULT '',
    "closed_at" timestamptz NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "closed_by_id" bigint NULL REFERENCES "public"."accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "company_id" bigint NOT NULL REFERENCES "vehicle_mgmt"."company" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS "vm_fleet_monthly_close_unique" ON "vehicle_mgmt"."fleet_monthly_close" ("company_id", "period_month", "target");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_monthly_close_period_month_2130_idx" ON "vehicle_mgmt"."fleet_monthly_close" ("period_month");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_monthly_close_target_82ca_idx" ON "vehicle_mgmt"."fleet_monthly_close" ("target");
CREATE INDEX IF NOT EXISTS "vehicle_mgmt_fleet_monthly_close_status_5c3f_idx" ON "vehicle_mgmt"."fleet_monthly_close" ("status");
'''


DROP_SCHEMA_TABLES_SQL = r'''
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_monthly_close" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_profit_monthly_snapshot" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_profit_adjustment" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_profit_raw_entry" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_profit_import_batch" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_profit_rule_version" CASCADE;
DROP TABLE IF EXISTS "vehicle_mgmt"."fleet_inspection_schedule" CASCADE;
'''


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_management', '0012_fleet_accident_case_manual_compensation'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='FleetInspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=32)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], db_index=True, default='scheduled', max_length=16)),
                ('memo', models.TextField(blank=True, default='')),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_inspections', to='vehicle_management.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_inspections', to='vehicle_management.vehicle')),
                ('vehicle_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='vehicle_management.fleetvehiclerecord')),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_inspection_schedule',
                'ordering': ['scheduled_date', 'vehicle_number', 'id'],
                'indexes': [
                    models.Index(fields=['company', 'scheduled_date'], name='vehicle_mgm_company_bd0c8a_idx'),
                    models.Index(fields=['company', 'status'], name='vehicle_mgm_company_fb8bd9_idx'),
                    models.Index(fields=['company', 'vehicle_number'], name='vehicle_mgm_company_531e62_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetProfitRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_profit_rule_versions', to='vehicle_management.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_profit_rule_version',
                'ordering': ['-created_at', '-id'],
                'constraints': [
                    models.UniqueConstraint(fields=['company', 'version'], name='vm_fleet_profit_rule_company_version_unique'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetProfitImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='applied', max_length=24)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_profit_import_batches', to='vehicle_management.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_profit_import_batch',
                'ordering': ['-created_at'],
                'constraints': [
                    models.UniqueConstraint(fields=['company', 'file_hash'], name='vm_fleet_profit_batch_company_hash_unique'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetProfitRawEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('cover', 'Cover'), ('depreciation', 'Depreciation'), ('residual', 'Residual'), ('insurance', 'Insurance'), ('subscription', 'Subscription'), ('accident', 'Accident'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=64)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('source_key', models.CharField(db_index=True, max_length=160)),
                ('vehicle_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('period_month', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_entries', to='vehicle_management.fleetprofitimportbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_profit_raw_entries', to='vehicle_management.company')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_profit_raw_entries', to='vehicle_management.vehicle')),
                ('vehicle_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_raw_entries', to='vehicle_management.fleetvehiclerecord')),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_profit_raw_entry',
                'ordering': ['source_sheet', 'source_row', 'id'],
                'constraints': [
                    models.UniqueConstraint(fields=['company', 'source_key'], name='vm_fleet_profit_raw_company_key_unique'),
                ],
                'indexes': [
                    models.Index(fields=['company', 'entry_type'], name='vehicle_mgm_company_541089_idx'),
                    models.Index(fields=['company', 'vehicle_number'], name='vehicle_mgm_company_752d2c_idx'),
                    models.Index(fields=['company', 'period_month'], name='vehicle_mgm_company_7c7c3f_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetProfitAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=32)),
                ('period_month', models.DateField(db_index=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.IntegerField(default=0)),
                ('evidence_file', models.FileField(blank=True, default='', upload_to='fleet_profit_evidence/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_profit_adjustments', to='vehicle_management.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_profit_adjustments', to='vehicle_management.vehicle')),
                ('vehicle_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_adjustments', to='vehicle_management.fleetvehiclerecord')),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_profit_adjustment',
                'ordering': ['-period_month', '-created_at'],
                'indexes': [
                    models.Index(fields=['company', 'period_month'], name='vehicle_mgm_company_11d0aa_idx'),
                    models.Index(fields=['company', 'vehicle_number'], name='vehicle_mgm_company_011684_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetProfitMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=32)),
                ('period_month', models.DateField(db_index=True)),
                ('revenue', models.IntegerField(default=0)),
                ('subscription_revenue', models.IntegerField(default=0)),
                ('customer_charges', models.IntegerField(default=0)),
                ('depreciation_cost', models.IntegerField(default=0)),
                ('insurance_cost', models.IntegerField(default=0)),
                ('repair_cost', models.IntegerField(default=0)),
                ('accident_cost', models.IntegerField(default=0)),
                ('other_cost', models.IntegerField(default=0)),
                ('operating_profit', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=0)),
                ('calculation', models.JSONField(blank=True, default=dict)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_profit_monthly_snapshots', to='vehicle_management.company')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='vehicle_management.fleetprofitruleversion')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_profit_monthly_snapshots', to='vehicle_management.vehicle')),
                ('vehicle_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_monthly_snapshots', to='vehicle_management.fleetvehiclerecord')),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_profit_monthly_snapshot',
                'ordering': ['-period_month', 'vehicle_number'],
                'constraints': [
                    models.UniqueConstraint(fields=['company', 'vehicle_number', 'period_month'], name='vm_fleet_profit_month_vehicle_unique'),
                ],
                'indexes': [
                    models.Index(fields=['company', 'period_month'], name='vehicle_mgm_company_e15ca5_idx'),
                    models.Index(fields=['company', 'is_closed'], name='vehicle_mgm_company_7c4cff_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FleetMonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(db_index=True)),
                ('target', models.CharField(db_index=True, default='profit', max_length=32)),
                ('status', models.CharField(db_index=True, default='open', max_length=24)),
                ('memo', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_monthly_closes', to='vehicle_management.company')),
            ],
            options={
                'db_table': 'vehicle_mgmt_fleet_monthly_close',
                'ordering': ['-period_month', 'target'],
                'constraints': [
                    models.UniqueConstraint(fields=['company', 'period_month', 'target'], name='vm_fleet_monthly_close_unique'),
                ],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_SCHEMA_TABLES_SQL, DROP_SCHEMA_TABLES_SQL),
            ],
            state_operations=state_operations,
        ),
    ]
