# Generated by Django 4.2.13 on 2026-05-03 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crew", "0002_round_yongcha_and_household_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("team_code", models.CharField(max_length=1, verbose_name="team code")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("device_token", models.CharField(blank=True, max_length=255, null=True, verbose_name="device token")),
                ("requested_at", models.DateTimeField(auto_now_add=True, verbose_name="requested at")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="approved at")),
                ("last_login_at", models.DateTimeField(blank=True, null=True, verbose_name="last login at")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "crew_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_app_user",
                        to="crew.crewmember",
                        verbose_name="crew member",
                    ),
                ),
            ],
            options={
                "verbose_name": "mobile app user",
                "verbose_name_plural": "mobile app users",
                "db_table": "mobile_app_users",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="MobilePassword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password_hash", models.CharField(max_length=128, verbose_name="password hash")),
                ("is_default", models.BooleanField(default=True, verbose_name="is default")),
                ("changed_at", models.DateTimeField(blank=True, null=True, verbose_name="changed at")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "mobile_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_record",
                        to="mobile.mobileappuser",
                        verbose_name="mobile user",
                    ),
                ),
            ],
            options={
                "verbose_name": "mobile password",
                "verbose_name_plural": "mobile passwords",
                "db_table": "mobile_passwords",
            },
        ),
    ]
