# Generated by Django 4.2.13 on 2026-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppMessageConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_overrides", models.JSONField(blank=True, default=dict, verbose_name="message overrides")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "mobile app message config",
                "verbose_name_plural": "mobile app message configs",
                "db_table": "mobile_app_message_config",
            },
        ),
    ]
