# Generated by Django 4.2.13 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0002_mobileappmessageconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileappuser",
            name="privacy_policy_agreed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="개인정보처리방침 동의 시각",
            ),
        ),
        migrations.AddField(
            model_name="mobileappuser",
            name="signup_completed",
            field=models.BooleanField(default=False, verbose_name="회원가입 완료"),
        ),
        migrations.AddField(
            model_name="mobileappuser",
            name="signup_completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="회원가입 완료 시각",
            ),
        ),
        migrations.AddField(
            model_name="mobileappuser",
            name="terms_agreed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="이용약관 동의 시각",
            ),
        ),
    ]
